name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    - name: Cache Playwright browsers
      uses: actions/cache@v5
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -e . --group dev
    - name: Install Playwright dependencies
      run: |
        python -m playwright install-deps
        shot-scraper install
        shot-scraper install -b firefox
        shot-scraper install -b webkit
    - name: Run tests
      run: |
        pytest
    - name: Check if cog needs to be run
      run: |
        cog --check docs/*.md
    - name: Run test examples
      run: |
        tests/run_examples.sh
    - name: Archive examples
      uses: actions/upload-artifact@v6
      with:
        name: examples-${{ matrix.python-version }}
        path: examples/*
